// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type SleepLog struct {
	ID              int64              `json:"id"`
	Date            pgtype.Date        `json:"date"`
	Bedtime         pgtype.Time        `json:"bedtime"`
	WakeTime        pgtype.Time        `json:"wake_time"`
	DurationMinutes int32              `json:"duration_minutes"`
	Quality         int16              `json:"quality"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
