// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sleep.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSleepLog = `-- name: CreateSleepLog :one

INSERT INTO sleep_logs (
    date,
    bedtime,
    wake_time,
    duration_minutes,
    quality,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, date, bedtime, wake_time, duration_minutes, quality, notes, created_at, updated_at
`

type CreateSleepLogParams struct {
	Date            pgtype.Date `json:"date"`
	Bedtime         pgtype.Time `json:"bedtime"`
	WakeTime        pgtype.Time `json:"wake_time"`
	DurationMinutes int32       `json:"duration_minutes"`
	Quality         int16       `json:"quality"`
	Notes           pgtype.Text `json:"notes"`
}

// Sleep Tracking queries for the Sleep Tracking module (Milestone 2, Issue #11).
// Generated code lives in api/db/sqlc/ via: cd api && sqlc generate
// Inserts a new sleep record and returns the persisted row.
// duration_minutes is calculated and supplied by the backend service (#12).
// A unique constraint on date means a duplicate date raises a uniqueness violation
// that #12 will translate into HTTP 409 Conflict.
func (q *Queries) CreateSleepLog(ctx context.Context, arg CreateSleepLogParams) (SleepLog, error) {
	row := q.db.QueryRow(ctx, createSleepLog,
		arg.Date,
		arg.Bedtime,
		arg.WakeTime,
		arg.DurationMinutes,
		arg.Quality,
		arg.Notes,
	)
	var i SleepLog
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Bedtime,
		&i.WakeTime,
		&i.DurationMinutes,
		&i.Quality,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSleepLogs = `-- name: ListSleepLogs :many
SELECT id, date, bedtime, wake_time, duration_minutes, quality, notes, created_at, updated_at
FROM sleep_logs
ORDER BY date DESC
LIMIT $1
OFFSET $2
`

type ListSleepLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Returns sleep records ordered newest first, with LIMIT/OFFSET pagination.
func (q *Queries) ListSleepLogs(ctx context.Context, arg ListSleepLogsParams) ([]SleepLog, error) {
	rows, err := q.db.Query(ctx, listSleepLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SleepLog
	for rows.Next() {
		var i SleepLog
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Bedtime,
			&i.WakeTime,
			&i.DurationMinutes,
			&i.Quality,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
