// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sleep.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSleepLog = `-- name: CreateSleepLog :one

INSERT INTO sleep_logs (
    date,
    bedtime,
    wake_time,
    duration_minutes,
    quality,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, date, bedtime, wake_time, duration_minutes, quality, notes, created_at, updated_at
`

type CreateSleepLogParams struct {
	Date            pgtype.Date `json:"date"`
	Bedtime         pgtype.Time `json:"bedtime"`
	WakeTime        pgtype.Time `json:"wake_time"`
	DurationMinutes int32       `json:"duration_minutes"`
	Quality         int16       `json:"quality"`
	Notes           pgtype.Text `json:"notes"`
}

// Sleep Tracking queries for the Sleep Tracking module (Milestone 2, Issue #11).
// Generated code lives in api/db/sqlc/ via: cd api && sqlc generate
// Inserts a new sleep record and returns the persisted row.
// duration_minutes is calculated and supplied by the backend service (#12).
// A unique constraint on date means a duplicate date raises a uniqueness violation
// that #12 will translate into HTTP 409 Conflict.
func (q *Queries) CreateSleepLog(ctx context.Context, arg CreateSleepLogParams) (SleepLog, error) {
	row := q.db.QueryRow(ctx, createSleepLog,
		arg.Date,
		arg.Bedtime,
		arg.WakeTime,
		arg.DurationMinutes,
		arg.Quality,
		arg.Notes,
	)
	var i SleepLog
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Bedtime,
		&i.WakeTime,
		&i.DurationMinutes,
		&i.Quality,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSleepLog = `-- name: DeleteSleepLog :execrows
DELETE FROM sleep_logs
WHERE id = $1
`

// Deletes a sleep record by id and returns the number of affected rows.
func (q *Queries) DeleteSleepLog(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSleepLog, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSleepStats = `-- name: GetSleepStats :one
SELECT
    COUNT(CASE WHEN date >= CURRENT_DATE - 6 THEN 1 END) AS count_7d,
    AVG(CASE WHEN date >= CURRENT_DATE - 6 THEN duration_minutes::double precision END) AS avg_duration_7d,
    AVG(CASE WHEN date >= CURRENT_DATE - 6 THEN quality::double precision END) AS avg_quality_7d,
    COUNT(*) AS count_30d,
    AVG(duration_minutes::double precision) AS avg_duration_30d,
    AVG(quality::double precision) AS avg_quality_30d
FROM sleep_logs
WHERE date >= CURRENT_DATE - 29
  AND date <= CURRENT_DATE
`

type GetSleepStatsRow struct {
	Count7d        int64         `json:"count_7d"`
	AvgDuration7d  pgtype.Float8 `json:"avg_duration_7d"`
	AvgQuality7d   pgtype.Float8 `json:"avg_quality_7d"`
	Count30d       int64         `json:"count_30d"`
	AvgDuration30d pgtype.Float8 `json:"avg_duration_30d"`
	AvgQuality30d  pgtype.Float8 `json:"avg_quality_30d"`
}

// Aggregates sleep statistics for the last 7 and 30 calendar days in a single query.
// 7-day window: [CURRENT_DATE - 6, CURRENT_DATE] inclusive (today + previous 6 days).
// 30-day window: [CURRENT_DATE - 29, CURRENT_DATE] inclusive (today + previous 29 days).
// Missing days are ignored; averages use only existing records as denominator.
// Returns NULL averages when no records exist in a window (record_count = 0).
// Future dates are explicitly excluded.
func (q *Queries) GetSleepStats(ctx context.Context) (GetSleepStatsRow, error) {
	row := q.db.QueryRow(ctx, getSleepStats)
	var i GetSleepStatsRow
	err := row.Scan(
		&i.Count7d,
		&i.AvgDuration7d,
		&i.AvgQuality7d,
		&i.Count30d,
		&i.AvgDuration30d,
		&i.AvgQuality30d,
	)
	return i, err
}

const listSleepLogs = `-- name: ListSleepLogs :many
SELECT id, date, bedtime, wake_time, duration_minutes, quality, notes, created_at, updated_at
FROM sleep_logs
ORDER BY date DESC
LIMIT $1
OFFSET $2
`

type ListSleepLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Returns sleep records ordered newest first, with LIMIT/OFFSET pagination.
func (q *Queries) ListSleepLogs(ctx context.Context, arg ListSleepLogsParams) ([]SleepLog, error) {
	rows, err := q.db.Query(ctx, listSleepLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SleepLog
	for rows.Next() {
		var i SleepLog
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Bedtime,
			&i.WakeTime,
			&i.DurationMinutes,
			&i.Quality,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSleepLog = `-- name: UpdateSleepLog :one
UPDATE sleep_logs
SET
    date = $2,
    bedtime = $3,
    wake_time = $4,
    duration_minutes = $5,
    quality = $6,
    notes = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, date, bedtime, wake_time, duration_minutes, quality, notes, created_at, updated_at
`

type UpdateSleepLogParams struct {
	ID              int64       `json:"id"`
	Date            pgtype.Date `json:"date"`
	Bedtime         pgtype.Time `json:"bedtime"`
	WakeTime        pgtype.Time `json:"wake_time"`
	DurationMinutes int32       `json:"duration_minutes"`
	Quality         int16       `json:"quality"`
	Notes           pgtype.Text `json:"notes"`
}

// Updates an existing sleep record and returns the persisted row.
// duration_minutes is recalculated and supplied by the backend service (#14).
func (q *Queries) UpdateSleepLog(ctx context.Context, arg UpdateSleepLogParams) (SleepLog, error) {
	row := q.db.QueryRow(ctx, updateSleepLog,
		arg.ID,
		arg.Date,
		arg.Bedtime,
		arg.WakeTime,
		arg.DurationMinutes,
		arg.Quality,
		arg.Notes,
	)
	var i SleepLog
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Bedtime,
		&i.WakeTime,
		&i.DurationMinutes,
		&i.Quality,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
